HD_COMPONENT_NAME	= heacore

HD_COMPONENT_VERS	=

HD_CXXTASK              = spman

HD_CXXTASK_SRC_cxx      = spman.cxx

HD_CXXFLAGS             = ${HD_STD_CXXFLAGS} -Wno-deprecated

HD_CXXLIBS		= ${HD_LFLAGS} ${HD_STD_CXXLIBS} -l${HEASP} ${XLIBS} ${SYSLIBS}

HD_INSTALL_TASKS	= ${HD_CXXTASK}

include ${HD_STD_MAKEFILE}

