HD_COMPONENT_NAME	= heacore

HD_COMPONENT_VERS	=

HD_CTASK                = Cspman

HD_CTASK_SRC_c          = Cspman.c

HD_CFLAGS               = ${HD_STD_CFLAGS}

HD_CLIBS		= ${HD_LFLAGS} -l${HEASP} ${HD_STD_CLIBS}

HD_INSTALL_TASKS	= ${HD_CTASK}

include ${HD_STD_MAKEFILE}

